CREATE TABLE [dbo].[News]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Title] NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(500) NOT NULL,
	[DateCreated] DATETIME NOT NULL,
	[UserCreated] NVARCHAR(50) NOT NULL,
	[DateModified] DATETIME NULL,
	[UserModified] NVARCHAR(50) NULL,
	[IsDeleted] BIT NOT NULL
)
GO

ALTER TABLE [dbo].[News] 
	ADD	CONSTRAINT [PK_News] PRIMARY KEY ([Id] DESC)
GO